#!/bin/bash

################################################################################
#       Script for generating the job script to extract non-rRNA reads         #
#                                                                              #
# This script will generate all the commands needed to align paired end fastqs #
# to a reference rRNA fasta. Script may need changing based on file            #
# name changes.                                                                #
#                                                                              #
# Author          : Harry Pollitt                                              #
# Email           : hap39@aber.ac.uk    hp508@exeter.ac.uk                     #
# GitHub          : https://github.com/Harry-Pollitt                           #
#                                                                              #
# Updated by Rebekah White October 2022.                                       #  
# Email           : rw617@exeter.ac.uk                                         #
# GitHub          : https://github.com/berk1835                                #
#                                                                              #
# To use, copy or symbolic link this script into the directory where your      #
# rRNA aligned BAM files are. Fastq files will be stored in a sub-directory.   #
# From inside that directory run the script:                                   #
#                                                                              #
# sh sortedbam_commands.sh                                                     #
#                                                                              #
# This will create a job script containing all the SAMTools                    #
# commands ready to submit to the queue.                                       #
#                                                                              #
################################################################################



cat <<\EOF > sortedbam_commands.sh
#!/bin/bash
#SBATCH --export=ALL # export all environment variables to the batch job
#SBATCH -D . # set working directory
#SBATCH -p pq # submit to the parallel queue
#SBATCH --time=10:00:00 # maximum walltime for the job
#SBATCH -A Research_Project-T110796 # research project to submit under
#SBATCH --nodes=2 # specify number of nodes
#SBATCH --ntasks-per-node=8 # specify number of processors per node
#SBATCH --mem=40G # specify bytes memory to reserve
#SBATCH --mail-type=END # send email at job completion
#SBATCH --mail-user=rw617@exeter.ac.uk # email address

# Commands you wish to run must go here, after the SLURM directives]
# load the modules required by the job
#module load BEDTools/2.27.1-foss-2016b
#module load SAMtools/1.5-foss-2016b

ref=/lustre/projects/Research_Project-T110796/Project_10762/el_paco_ref/el_paco_ref/rRNA-reference.fasta
EOF


###################################################################################
#
# Loop to generate commands to convert rRNA aligned bam to fastqs of non-rRNA reads
#
###################################################################################


for fname in /lustre/projects/Research_Project-T110796/Project_10762/ages_alignments/fastqs/*rRNA_alignment.sam.gz.bam
do
        SAMPLE=${fname%_rRNA*}
        printf "samtools sort -n "${SAMPLE}_rRNA_alignment.sam.gz.bam" -o "${SAMPLE}_sorted.bam" | bedtools bamtofastq -i "${SAMPLE}_sorted.bam" -fq "${SAMPLE}_filtered_R1.fastq" -fq2 "${SAMPLE}_filtered_R2.fastq"\n" >> sortedbam_commands.sh

done


